CXXFLAGS = -Wall -Wextra

all: hellotass echoargs echoname echoage

hellotass: hellotass.o
	$(LINK.cc) $^ -o $@

echoargs: echoargs.o
	$(LINK.cc) $^ -o $@

echoname: echoname.o
	$(LINK.cc) $^ -o $@

echoage: echoage.o
	$(LINK.cc) $^ -o $@
